/* ============================================================
   GRUPO MEC PROPIEDADES — Datos de emprendimientos
   Para agregar un nuevo emprendimiento, sumá un objeto más
   a este arreglo respetando la misma estructura.
   Las imágenes son placeholders (gradientes vía CSS/clase
   "ph-<n>"); reemplazá "image" e "images" por rutas reales
   cuando tengas la fotografía (ej: "images/desarrollos/santa-teresita/hero.jpg").
   ============================================================ */

const DEVELOPMENTS = [
  {
    id: "la-limena",
    name: "La Limeña",
    location: "Lima, partido de Zárate, Buenos Aires",
    status: "En desarrollo",
    shortDescription: "Barrio Abierto — En una antigua plantación de arándanos, nace un lugar para construir tu futuro.",
    description: "En una antigua plantación de arándanos, nace La Limeña. Un lugar donde sus propietarios decidieron darle una nueva vida al campo, transformándolo en un espacio pensado para que nuevas familias puedan construir sus proyectos, sus recuerdos y su futuro. Ubicado en la localidad de Lima, partido de Zárate, La Limeña combina la tranquilidad de la naturaleza con una excelente conectividad, ofreciendo una oportunidad única para vivir o invertir.",
    image: "images/desarrollos/la-limena-portada.jpg",
    images: ["images/desarrollos/la-limena-aerea.jpg", "images/desarrollos/la-limena-pileta.jpg", "images/desarrollos/la-limena-quincho.jpg"],
    features: [
      "Barrio abierto, sin expensas",
      "Lotes de 300 a 425 m²",
      "Red de agua y energía eléctrica",
      "Excelente acceso desde la Ruta Nacional N.º 9",
      "Ideal para vivienda permanente, casa de fin de semana o inversión"
    ],
    services: ["Red de agua", "Energía eléctrica"],
    price: "Lotes desde USD 17.000 · Anticipo desde USD 2.000 · Hasta 60 cuotas fijas en dólares",
    lots: "266 lotes",
    surface: "De 300 a 425 m²",
    quickFacts: ["De 300 a 425 m²", "Zárate", "Financiación en dólares"],
    mapQuery: "-34.0414973,-59.206031",
    masterplanImage: "images/masterplanes/la-limena.jpg",
    virtualTourUrl: "https://datastudio.google.com/u/0/reporting/48ba360b-8c64-4c19-b94c-e8a176554761/page/kd9TF",
  },
  {
    id: "santa-teresita",
    name: "Barrio Santa Teresita",
    location: "Santa Teresita, partido de Zárate, Buenos Aires",
    status: "Preventa",
    shortDescription: "Un nuevo barrio para comenzar una nueva historia.",
    description: "A solo minutos del centro de Zárate, Santa Teresita nace con la visión de crear un barrio donde cada lote sea el punto de partida de un nuevo proyecto de vida. Un espacio pensado para quienes sueñan con construir su hogar o realizar una inversión segura en una de las zonas con mayor crecimiento de la ciudad. Con una ubicación estratégica, infraestructura planificada y todos los servicios esenciales, Santa Teresita combina calidad de vida, accesibilidad y un gran potencial de valorización. A solo 9 minutos del centro de Zárate y con excelente acceso desde la Ruta Nacional N.º 9.",
    image: "images/desarrollos/santa-teresita-portada.jpg",
    images: ["images/desarrollos/santa-teresita-1.jpg", "images/desarrollos/santa-teresita-2.jpg", "images/desarrollos/santa-teresita-3.jpg"],
    features: [
      "Barrio abierto, sin expensas",
      "Lotes de 200 a 290 m²",
      "Infraestructura planificada",
      "Espacios verdes",
      "Cercanía a escuelas y universidades",
      "Acceso a transporte público",
      "Ideal para vivienda permanente o inversión"
    ],
    services: ["Red de luz", "Agua", "Cloacas"],
    price: "Lotes desde USD 15.500 · Anticipo desde USD 2.860 · Hasta 72 cuotas fijas en dólares",
    lots: "+180 lotes",
    surface: "De 200 a 290 m²",
    quickFacts: ["De 200 a 290 m²", "Zárate", "Financiación en dólares"],
    mapQuery: "-34.0879837,-59.0517466",
    masterplanImage: "images/masterplanes/santa-teresita.jpg",
    virtualTourUrl: "https://datastudio.google.com/u/0/reporting/d932d114-079f-4cec-9a7e-9c3e9cbd7a83/page/p_49orv5s14d",
    interactiveMapUrl: "https://eperondi2015.github.io/Tablero-Santa-Teresita/Mapa_Clientes_Santa_Teresita.html",
  },
  {
    id: "atardeceres-de-matheu",
    name: "Atardeceres de Matheu",
    location: "Ruta Provincial 25, Matheu, partido de Escobar, Buenos Aires",
    status: "Preventa",
    shortDescription: "Un nuevo proyecto que transforma Matheu.",
    description: "Atardeceres de Matheu es un desarrollo que llega para impulsar el crecimiento de la zona, ofreciendo una excelente oportunidad para quienes buscan invertir o proyectar su futuro. Un barrio nuevo, en pleno desarrollo, con una ubicación estratégica y gran potencial de valorización.",
    image: "images/desarrollos/atardeceres-de-matheu-portada.jpg",
    images: ["images/desarrollos/atardeceres-de-matheu-1.jpg", "images/desarrollos/atardeceres-de-matheu-2.jpg", "images/desarrollos/atardeceres-de-matheu-3.jpg"],
    features: [
      "Barrio nuevo, en desarrollo",
      "Excelente conectividad",
      "Lotes desde 300 m²",
      "Ideal para vivienda o inversión",
      "Gran proyección de crecimiento y valorización"
    ],
    services: ["Luz", "Agua", "Cloaca"],
    price: "Lotes desde USD 25.000",
    lots: "Consultar disponibilidad",
    surface: "Desde 300 m²",
    quickFacts: ["Escobar", "Desde 300 m²", "Zona de crecimiento"],
    mapQuery: "-34.3815187,-58.8236347",
    masterplanImage: "images/masterplanes/atardeceres-de-matheu.jpg",
  },
  {
    id: "quebrada-de-cardales",
    name: "Quebrada de Cardales",
    location: "Los Cardales, partido de Exaltación de la Cruz, Buenos Aires",
    status: "Últimos lotes",
    shortDescription: "Naturaleza, espacio y calidad de vida.",
    description: "Quebrada de Cardales es un barrio abierto pensado para quienes buscan vivir rodeados de naturaleza, con amplios lotes y la tranquilidad del campo, sin resignar una excelente conectividad. Un lugar ideal para construir, disfrutar e invertir.",
    image: "images/desarrollos/quebrada-de-cardales-portada.jpg",
    images: ["images/desarrollos/quebrada-de-cardales-1.jpg", "images/desarrollos/quebrada-de-cardales-2.jpg", "images/desarrollos/quebrada-de-cardales-3.jpg"],
    features: [
      "Barrio abierto, sin expensas",
      "Lotes desde 1.000 m²",
      "Entorno natural y amplios espacios verdes",
      "Excelente acceso desde las rutas 4, 6 y Panamericana"
    ],
    services: ["Red de energía eléctrica y agua"],
    price: "Lotes desde USD 56.000 · Hasta 48 cuotas fijas desde USD 1.412 · Financiación en pesos a consultar",
    lots: "Últimas 12 unidades",
    surface: "Desde 1.000 m²",
    quickFacts: ["Últimas 12 unidades", "Desde 1.000 m²", "Barrio abierto sin expensas"],
    mapQuery: "-34.3057281,-58.9376338",
    masterplanImage: "images/masterplanes/quebrada-de-cardales.jpg",
  },
  {
    id: "parada-robles",
    name: "Parada Robles III",
    location: "Exaltación de la Cruz, Buenos Aires",
    status: "Preventa",
    shortDescription: "Tu lugar en el campo, cerca de todo.",
    description: "Hay lugares que invitan a bajar el ritmo y empezar a proyectar una vida más tranquila. Parada Robles III combina naturaleza, amplitud y excelente conectividad, ofreciendo el espacio ideal para construir la casa que siempre imaginaste. A minutos de Capilla del Señor y con excelente acceso por Ruta 6.",
    image: "images/desarrollos/parada-robles-portada.jpg",
    images: ["images/desarrollos/parada-robles-portada.jpg"],
    features: [
      "Barrio abierto, sin expensas",
      "Lotes desde 1.500 m²",
      "Entorno natural y consolidado",
      "Excelente conectividad hacia Capital, Pilar, Campana y Zárate",
      "Ideal para vivienda permanente, casa de fin de semana o inversión"
    ],
    services: ["Consultar servicios disponibles"],
    price: "Lotes desde $53.000.000 · Financiados en pesos hasta 84 cuotas (plan de 114 bolsas de cemento)",
    lots: "Consultar disponibilidad",
    surface: "Desde 1.500 m²",
    quickFacts: ["Desde 1.500 m²", "Exaltación de la Cruz", "Financiación en pesos"],
    mapQuery: "Exaltación de la Cruz, Buenos Aires",
    masterplanImage: "images/masterplanes/parada-robles.jpg",
  },

  /* ---- Nuevos barrios y productos — descripciones breves, editar libremente ---- */

  {
    id: "aires-de-la-florida",
    name: "Aires de La Florida",
    location: "La Florida, partido de Zárate, Buenos Aires",
    status: "En desarrollo",
    shortDescription: "Un lugar para vivir con tranquilidad.",
    description: "Aires de La Florida es un barrio abierto pensado para quienes buscan la paz de un entorno natural sin alejarse de la ciudad. Un espacio donde cada lote invita a comenzar una nueva historia.",
    image: "images/desarrollos/aires-de-la-florida-portada.jpg",
    images: ["images/desarrollos/aires-de-la-florida-1.jpg", "images/desarrollos/aires-de-la-florida-2.jpg"],
    features: [
      "Barrio abierto, sin expensas",
      "Entorno natural",
      "Ideal para vivienda o inversión"
    ],
    services: ["Energía eléctrica"],
    price: "Lotes desde USD 23.000 · Consultar planes de financiación",
    lots: "Consultar disponibilidad",
    surface: "A confirmar",
    quickFacts: ["Zárate", "Entorno natural", "Financiación disponible"],
    mapQuery: "-34.1414796,-59.0872964",
    masterplanImage: "images/masterplanes/aires-de-la-florida.jpg",
  },
  {
    id: "la-escapada",
    name: "La Escapada",
    location: "Camino a Capilla del Señor, Exaltación de la Cruz, Buenos Aires",
    status: "Preventa",
    shortDescription: "El lugar donde el campo se convierte en tu estilo de vida.",
    description: "La Escapada es un barrio de chacras pensado para quienes buscan disfrutar de la naturaleza, la tranquilidad y los amplios espacios, sin resignar una excelente conectividad. Un entorno ideal para vivir, descansar o invertir. Acceso totalmente asfaltado, con excelente conexión con las rutas 193 y 9.",
    image: "images/desarrollos/la-escapada-portada.jpg",
    images: ["images/desarrollos/la-escapada-1.jpg"],
    features: [
      "Barrio de chacras",
      "Lotes desde 10.000 m²",
      "Entorno de quintas, desarrollos rurales y canchas de polo",
      "Amplios espacios verdes y gran privacidad",
      "Ideal para vivienda permanente, casa de fin de semana o inversión"
    ],
    services: ["Acceso totalmente asfaltado"],
    price: "Lotes desde USD 45.000",
    lots: "Consultar disponibilidad",
    surface: "Desde 10.000 m²",
    quickFacts: ["Desde 10.000 m²", "Barrio de chacras", "Acceso asfaltado"],
    mapQuery: "-34.1781091,-59.0912508",
    masterplanImage: "images/masterplanes/la-escapada.jpg",
  },
  {
    id: "el-campo-fincas",
    name: "El Campo – Fincas Exclusivas",
    location: "Los Cardales, partido de Exaltación de la Cruz, Buenos Aires",
    status: "En desarrollo",
    shortDescription: "Viví el campo, todos los días.",
    description: "El Campo – Fincas Exclusivas es un barrio privado ubicado en Los Cardales, diseñado para quienes buscan naturaleza, tranquilidad y amplios espacios, en un entorno de gran categoría y excelente conectividad.",
    image: "images/desarrollos/el-campo-fincas-portada.jpg",
    images: ["images/desarrollos/el-campo-fincas-portada.jpg", "images/desarrollos/el-campo-fincas-real-1.jpg", "images/desarrollos/el-campo-fincas-real-2.jpg", "images/desarrollos/el-campo-fincas-real-3.jpg", "images/desarrollos/el-campo-fincas-real-4.jpg", "images/desarrollos/el-campo-fincas-real-5.jpg"],
    features: [
      "Barrio privado",
      "Lotes desde 1.300 m²",
      "Entorno natural con amplios espacios verdes",
      "Excelente acceso desde la Ruta 6 y Panamericana",
      "Ideal para vivienda permanente o de fin de semana"
    ],
    services: ["Luz", "Agua", "Cloaca"],
    price: "Lotes desde USD 43.000",
    lots: "Consultar disponibilidad",
    surface: "Desde 1.300 m²",
    quickFacts: ["Los Cardales", "Desde 1.300 m²", "Barrio privado"],
    mapQuery: "-34.3002778,-58.9264741",
    masterplanImage: "images/masterplanes/el-campo-fincas.jpg",
  },
  {
    id: "el-naudir",
    name: "El Naudir Aguas Privadas",
    location: "Belén de Escobar, Buenos Aires",
    status: "En desarrollo",
    shortDescription: "Viví cada día frente al agua.",
    description: "El Naudir Aguas Privadas es un barrio náutico pensado para quienes buscan combinar naturaleza, confort y calidad de vida. Con amplios espejos de agua y un entorno exclusivo, ofrece el escenario ideal para vivir, disfrutar y realizar una inversión de gran valor.",
    image: "images/desarrollos/el-naudir-portada.jpg",
    images: ["images/desarrollos/el-naudir-portada.jpg", "images/desarrollos/el-naudir-real-1.jpg", "images/desarrollos/el-naudir-real-2.jpg", "images/desarrollos/el-naudir-real-3.jpg", "images/desarrollos/el-naudir-real-4.jpg"],
    features: [
      "Barrio náutico",
      "Lotes internos y al agua",
      "Laguna navegable y salida al río",
      "Ideal para vivienda permanente o inversión"
    ],
    services: ["Infraestructura y servicios de primer nivel"],
    price: "Lotes al agua desde USD 60.000",
    lots: "Consultar disponibilidad",
    surface: "A confirmar",
    quickFacts: ["Barrio náutico", "Escobar", "Laguna navegable"],
    mapQuery: "-34.3170126,-58.7419961",
    masterplanImage: "images/masterplanes/el-naudir.jpg",
  },
  {
    id: "naves-industriales",
    name: "Naves de Almacenamiento Logístico",
    location: "Zárate, Buenos Aires",
    status: "Consultar disponibilidad",
    shortDescription: "Infraestructura estratégica para potenciar su operación.",
    description: "Naves logísticas diseñadas para empresas que buscan eficiencia, conectividad y una ubicación privilegiada dentro del principal corredor logístico del país. Espacios listos para operar, con infraestructura de primer nivel y excelentes accesos para transporte de cargas. A 4 km de la Ruta Nacional 9, con conexión directa a Ruta 6, el Parque Industrial Zárate y la zona portuaria.",
    image: "images/desarrollos/naves-industriales-portada.jpg",
    images: ["images/desarrollos/naves-industriales-1.jpg", "images/desarrollos/naves-industriales-2.jpg", "images/desarrollos/naves-industriales-3.jpg"],
    features: [
      "Naves desde 1.000 hasta 3.500 m²",
      "Más de 15.000 m² de superficie cubierta",
      "Playa de maniobras para transporte pesado",
      "Balanza para camiones",
      "Silo",
      "Amplios accesos logísticos internos",
      "Excelente conectividad regional"
    ],
    services: ["Alquiler y venta"],
    price: "Consultar disponibilidad",
    lots: "Consultar disponibilidad",
    surface: "Desde 1.000 hasta 3.500 m²",
    quickFacts: ["Zárate", "Desde 1.000 m²", "Alquiler y venta"],
    mapQuery: "-34.0897823,-59.0689081",
    hasMasterplan: false,
  },
  {
    id: "macrolotes",
    name: "Macrolotes",
    location: "Corredor norte y otros puntos de la Provincia de Buenos Aires",
    status: "Consultar disponibilidad",
    shortDescription: "Tierra con potencial. Proyectos que transforman.",
    description: "En Grupo MEC Propiedades impulsamos desarrollos inmobiliarios en ubicaciones estratégicas del corredor norte de la Provincia de Buenos Aires. Contamos con un banco de tierras en distintos puntos, pensado para desarrolladores e inversores que buscan proyectos de mayor escala. Consultanos para mayor información sobre cada oportunidad.",
    image: "images/desarrollos/macrolotes-portada.jpg",
    images: ["images/desarrollos/macrolotes-portada.jpg", "ph-3", "ph-4", "ph-2"],
    features: [
      "Exaltación de la Cruz — 183 hectáreas",
      "Escobar — 100 hectáreas",
      "Los Cardales — 74 hectáreas",
      "Lima — 18 hectáreas",
      "Pilar — parcelas desde 2 hectáreas, ideales para townhouses y condominios",
      "Pilar — fracción de 13 hectáreas con laguna",
      "Zárate — predio de 2 hectáreas sobre Ruta Provincial 6",
      "Escobar (Zona Puertos) — macrolotes comerciales"
    ],
    services: ["Consultar según ubicación"],
    price: "Consultar disponibilidad",
    lots: "Banco de tierras",
    surface: "Desde 2 hectáreas",
    quickFacts: ["Banco de tierras", "Corredor norte", "Desde 2 hectáreas"],
    mapQuery: "Buenos Aires, Argentina",
    hasMasterplan: false,
    hasGallery: false,
    whatsappOverride: "paula",
    landBankPoints: [
      { name: "Exaltación de la Cruz", detail: "183 hectáreas", lat: -34.3556944, lng: -59.0543333 },
      { name: "Escobar", detail: "100 hectáreas", lat: -34.3040278, lng: -58.8002778 },
      { name: "Los Cardales", detail: "74 hectáreas", lat: -34.283822654592704, lng: -58.92041921534119 },
      { name: "Lima", detail: "18 hectáreas", lat: -34.0486667, lng: -59.2051111 },
      { name: "Pilar — Parcelas desde 2 ha", detail: "Ideales para townhouses y condominios", lat: -34.42241764959923, lng: -58.8868412865059 },
      { name: "Pilar — Fracción con laguna", detail: "13 hectáreas", lat: -34.4312778, lng: -58.9435556 },
      { name: "Zárate", detail: "Predio de 2 hectáreas sobre Ruta Provincial 6", lat: -34.1272778, lng: -59.0139167 },
      { name: "Escobar — Zona Puertos", detail: "Macrolotes comerciales", lat: -34.3280278, lng: -58.7393889 }
    ],
  },
  {
    id: "inversiones-pool-de-rentas",
    name: "Inversiones - Pool de Rentas",
    location: "Cataratas del Iguazú y Valle de Uco, Mendoza",
    status: "Consultar disponibilidad",
    shortDescription: "Oportunidades de inversión en hotelería y rentas en dos de los destinos turísticos de mayor proyección del país.",
    description: "Grupo MEC ofrece oportunidades de inversión en pool de rentas, con habitaciones hoteleras operadas por cadenas internacionales, locales comerciales y oficinas en Cataratas del Iguazú y en el Valle de Uco, Mendoza. Una de las oportunidades disponibles es Four Points by Sheraton Iguazú: convertite en propietario de una habitación administrada por Marriott International y obtené ingresos sin preocuparte por la gestión, a solo 18 minutos del Parque Nacional Iguazú, una de las Siete Maravillas Naturales del Mundo.",
    image: "images/desarrollos/inversiones-pool-de-rentas-portada.jpg",
    images: ["images/desarrollos/inversiones-pool-de-rentas-portada.jpg", "ph-1", "ph-3", "ph-5"],
    features: [
      "Four Points by Sheraton Iguazú — Marriott International",
      "Obra con más del 60% de avance · Entrega estimada diciembre 2027",
      "Administración hotelera profesional",
      "Equipamiento y amoblamiento",
      "Locales comerciales y oficinas",
      "También disponible: Valle de Uco, Mendoza"
    ],
    services: ["Consultar según proyecto"],
    price: "Consultar disponibilidad",
    lots: "Consultar disponibilidad",
    surface: "A confirmar",
    quickFacts: ["Pool de rentas", "Four Points by Sheraton", "Cataratas del Iguazú"],
    mapQuery: "Puerto Iguazú, Misiones, Argentina",
    hasGallery: false,
    whatsappOverride: "paula",
    hasMasterplan: false,
  }
];

// Utilidad para obtener un emprendimiento por id
function getDevelopmentById(id){
  return DEVELOPMENTS.find(d => d.id === id);
}
