/* ============================================================
   GRUPO MEC PROPIEDADES — Datos de emprendimientos
   Para agregar un nuevo emprendimiento, sumá un objeto más
   a este arreglo respetando la misma estructura.
   Las imágenes son placeholders (gradientes vía CSS/clase
   "ph-<n>"); reemplazá "image" e "images" por rutas reales
   cuando tengas la fotografía (ej: "images/desarrollos/santa-teresita/hero.jpg").
   ============================================================ */

const DEVELOPMENTS = [
  {
    id: "la-limena",
    name: "La Limeña",
    location: "Salto, Buenos Aires",
    status: "En desarrollo",
    shortDescription: "Un desarrollo pensado para el descanso familiar, rodeado de espacios verdes y con excelente conectividad.",
    description: "La Limeña propone un estilo de vida en contacto con el entorno natural, sin resignar cercanía a los centros urbanos. El desarrollo incorpora amplias calles arboladas, espacios comunes y una traza pensada para maximizar la privacidad de cada lote.",
    image: "images/desarrollos/la-limena-portada.jpg",
    images: ["images/desarrollos/la-limena-aerea.jpg", "images/desarrollos/la-limena-pileta.jpg", "images/desarrollos/la-limena-quincho.jpg"],
    features: [
      "Lotes desde 500 m²",
      "Financiación en pesos",
      "Espacios verdes comunes",
      "Circulación interna arbolada",
      "A 5 min de la Ruta 6",
      "Seguridad perimetral"
    ],
    services: [
      "Red eléctrica",
      "Agua potable de red",
      "Calles internas mejoradas",
      "Forestación",
      "Portal de ingreso"
    ],
    price: "Consultar financiación",
    lots: "266 lotes",
    surface: "Desde 500 m²",
    quickFacts: ["266 lotes", "Barrio abierto", "Circulación interna arbolada"],
    mapQuery: "-34.0414973,-59.206031",
  },
  {
    id: "santa-teresita",
    name: "Barrio Santa Teresita",
    location: "Zárate, Buenos Aires",
    status: "Preventa",
    shortDescription: "Barrio abierto con lotes de gran superficie, pensado para vivir en contacto con la naturaleza a minutos del centro.",
    description: "Barrio Santa Teresita combina la tranquilidad de un entorno abierto con la cercanía a los principales accesos de la zona. Sus lotes fueron diseñados para dar lugar a proyectos de vivienda familiar con amplios espacios verdes, en una ubicación estratégica de fuerte crecimiento y valorización.",
    image: "images/desarrollos/santa-teresita-portada.jpg",
    images: ["images/desarrollos/santa-teresita-1.jpg", "images/desarrollos/santa-teresita-2.jpg", "images/desarrollos/santa-teresita-3.jpg"],
    features: [
      "Lotes desde 600 m²",
      "Financiación directa",
      "Barrio abierto",
      "Ingreso pavimentado",
      "Fácil acceso a Ruta 9",
      "Zona en expansión"
    ],
    services: [
      "Red eléctrica subterránea",
      "Agua de red",
      "Alumbrado público",
      "Forestación de calles",
      "Portal de acceso"
    ],
    price: "Consultar financiación",
    lots: "+180 lotes",
    surface: "Desde 600 m²",
    quickFacts: ["+180 lotes", "Desde 600 m²", "Barrio abierto sin expensas"],
    mapQuery: "-34.0879837,-59.0517466",
  },
  {
    id: "atardeceres-de-matheu",
    name: "Atardeceres de Matheu",
    location: "Matheu, Escobar",
    status: "Preventa",
    shortDescription: "Nuevo desarrollo en preventa en una de las localidades de mayor crecimiento de Escobar.",
    description: "Atardeceres de Matheu es un desarrollo en preventa ubicado en Matheu, partido de Escobar, en una zona de fuerte crecimiento y buena conectividad. (Descripción breve a completar con más detalle.)",
    image: "images/desarrollos/atardeceres-de-matheu-portada.jpg",
    images: ["images/desarrollos/atardeceres-de-matheu-1.jpg", "images/desarrollos/atardeceres-de-matheu-2.jpg", "images/desarrollos/atardeceres-de-matheu-3.jpg"],
    features: ["Preventa con condiciones preferenciales", "Zona de crecimiento", "Financiación disponible"],
    services: ["Servicios a definir según etapa de obra"],
    price: "Consultar financiación",
    lots: "Consultar disponibilidad",
    surface: "A confirmar",
    quickFacts: ["Escobar", "Zona de crecimiento", "Financiación disponible"],
    mapQuery: "-34.3815187,-58.8236347",
  },
  {
    id: "quebrada-de-cardales",
    name: "Quebrada de Cardales",
    location: "Cardales, Campana",
    status: "Últimos lotes",
    shortDescription: "Últimas unidades disponibles en una de las zonas de mayor revalorización de la región de Cardales.",
    description: "Quebrada de Cardales es un desarrollo consolidado, con la mayoría de sus lotes ya construidos y una comunidad activa. Las últimas unidades disponibles ofrecen la oportunidad de sumarse a un barrio ya en marcha, con todos los servicios funcionando.",
    image: "images/desarrollos/quebrada-de-cardales-portada.jpg",
    images: ["images/desarrollos/quebrada-de-cardales-1.jpg", "images/desarrollos/quebrada-de-cardales-2.jpg", "images/desarrollos/quebrada-de-cardales-3.jpg"],
    features: [
      "Lotes desde 700 m²",
      "Barrio consolidado",
      "Financiación disponible",
      "Cercanía al río Luján",
      "Área de forestación nativa",
      "Acceso pavimentado"
    ],
    services: [
      "Red eléctrica",
      "Agua de red",
      "Alumbrado LED",
      "Calles pavimentadas",
      "Espacios recreativos"
    ],
    price: "Consultar financiación",
    lots: "Últimas 12 unidades",
    surface: "Desde 700 m²",
    quickFacts: ["Últimas 12 unidades", "Desde 700 m²", "Barrio consolidado"],
    mapQuery: "-34.3057281,-58.9376338",
  },
  {
    id: "parada-robles",
    name: "Parada Robles",
    location: "Exaltación de la Cruz, Buenos Aires",
    status: "Preventa",
    shortDescription: "Nuevo lanzamiento sobre uno de los corredores de mayor crecimiento inmobiliario del norte del GBA.",
    description: "Parada Robles llega como el nuevo desarrollo de Grupo MEC en una de las zonas más demandadas del corredor norte. Con una traza pensada para amplios lotes y espacios verdes compartidos, es una oportunidad de inversión en preventa con condiciones preferenciales.",
    image: "images/desarrollos/parada-robles-portada.jpg",
    images: ["images/desarrollos/parada-robles-portada.jpg", "ph-5", "ph-6", "ph-1", "ph-2", "ph-3"],
    features: [
      "Lotes desde 550 m²",
      "Preventa con condiciones preferenciales",
      "Corredor de alta demanda",
      "Cercanía a Ruta 8",
      "Diseño paisajístico",
      "Plusvalía proyectada alta"
    ],
    services: [
      "Red eléctrica proyectada",
      "Provisión de agua",
      "Calles internas",
      "Forestación",
      "Portal de acceso controlado"
    ],
    price: "Consultar financiación",
    lots: "+95 lotes",
    surface: "Desde 550 m²",
    quickFacts: ["+95 lotes", "Desde 550 m²", "Corredor de alta demanda"],
    mapQuery: "Ruta 8 km 67, Pilar, Buenos Aires",
  },

  /* ---- Nuevos barrios y productos — descripciones breves, editar libremente ---- */

  {
    id: "aires-de-la-florida",
    name: "Aires de La Florida",
    location: "Exaltación de la Cruz, Buenos Aires",
    status: "En desarrollo",
    shortDescription: "Barrio abierto en una zona tranquila del corredor norte, ideal para vivienda familiar.",
    description: "Aires de La Florida propone lotes en un entorno abierto y arbolado, pensado para quienes buscan calidad de vida sin resignar cercanía a los principales accesos del corredor norte. (Descripción breve a completar con más detalle.)",
    image: "images/desarrollos/aires-de-la-florida-portada.jpg",
    images: ["images/desarrollos/aires-de-la-florida-1.jpg", "images/desarrollos/aires-de-la-florida-2.jpg"],
    features: ["Lotes de buena superficie", "Zona tranquila", "Financiación disponible", "Cercanía a accesos principales"],
    services: ["Red eléctrica", "Agua de red", "Calles internas", "Forestación"],
    price: "Consultar financiación",
    lots: "Consultar disponibilidad",
    surface: "A confirmar",
    quickFacts: ["Corredor norte", "Zona tranquila", "Financiación disponible"],
    mapQuery: "-34.1414796,-59.0872964",
  },
  {
    id: "la-escapada",
    name: "La Escapada",
    location: "Exaltación de la Cruz, Buenos Aires",
    status: "Preventa",
    shortDescription: "Nuevo lanzamiento en preventa, pensado para el descanso y la vida al aire libre.",
    description: "La Escapada es un desarrollo en preventa orientado a quienes buscan un espacio propio para el fin de semana o la vida permanente, en un entorno natural del corredor norte. (Descripción breve a completar con más detalle.)",
    image: "images/desarrollos/la-escapada-portada.jpg",
    images: ["images/desarrollos/la-escapada-1.jpg"],
    features: ["Preventa con condiciones preferenciales", "Entorno natural", "Financiación disponible"],
    services: ["Servicios a definir según etapa de obra"],
    price: "Consultar financiación",
    lots: "Consultar disponibilidad",
    surface: "A confirmar",
    quickFacts: ["Corredor norte", "Entorno natural", "Financiación disponible"],
    mapQuery: "-34.1781091,-59.0912508",
  },
  {
    id: "el-campo-fincas",
    name: "El Campo Fincas",
    location: "Cardales, Campana",
    status: "En desarrollo",
    shortDescription: "Fincas de mayor superficie para quienes buscan más espacio, verde y privacidad.",
    description: "El Campo Fincas ofrece unidades de mayor superficie que un lote tradicional, pensadas para proyectos con más espacio verde y privacidad, en la zona de Cardales. (Descripción breve a completar con más detalle.)",
    image: "images/desarrollos/el-campo-fincas-portada.jpg",
    images: ["images/desarrollos/el-campo-fincas-portada.jpg", "ph-4", "ph-3", "ph-5"],
    features: ["Fincas de gran superficie", "Privacidad", "Zona de Cardales", "Financiación disponible"],
    services: ["Servicios a definir según etapa de obra"],
    price: "Consultar financiación",
    lots: "Consultar disponibilidad",
    surface: "A confirmar",
    quickFacts: ["Cardales", "Fincas de gran superficie", "Privacidad"],
    mapQuery: "-34.3002778,-58.9264741",
  },
  {
    id: "el-naudir",
    name: "Barrio Cerrado El Naudir",
    location: "Ingeniero Maschwitz, Escobar",
    status: "En desarrollo",
    shortDescription: "Barrio cerrado con espejo de agua, seguridad las 24 horas y amenities.",
    description: "Barrio Cerrado El Naudir combina seguridad, amenities y un entorno de aguas privadas en una de las zonas más buscadas de Escobar. (Descripción breve a completar con más detalle.)",
    image: "images/desarrollos/el-naudir-portada.jpg",
    images: ["images/desarrollos/el-naudir-portada.jpg", "ph-4", "ph-6", "ph-3"],
    features: ["Barrio cerrado", "Aguas privadas", "Seguridad 24 hs", "Amenities"],
    services: ["Servicios a definir según etapa de obra"],
    price: "Consultar financiación",
    lots: "Consultar disponibilidad",
    surface: "A confirmar",
    quickFacts: ["Barrio cerrado", "Escobar"],
    mapQuery: "-34.3170126,-58.7419961",
  },
  {
    id: "naves-industriales",
    name: "Naves Industriales",
    location: "Corredor norte, Buenos Aires",
    status: "Consultar disponibilidad",
    shortDescription: "Naves industriales y depósitos en puntos estratégicos del corredor norte.",
    description: "Grupo MEC ofrece naves industriales y depósitos en ubicaciones estratégicas del corredor norte, ideales para logística, almacenamiento o producción. (Descripción breve a completar con más detalle.)",
    image: "images/desarrollos/naves-industriales-portada.jpg",
    images: ["images/desarrollos/naves-industriales-1.jpg", "images/desarrollos/naves-industriales-2.jpg", "images/desarrollos/naves-industriales-3.jpg"],
    features: ["Distintas superficies disponibles", "Ubicación estratégica", "Fácil acceso vial"],
    services: ["Servicios a definir según unidad"],
    price: "Consultar disponibilidad",
    lots: "Consultar disponibilidad",
    surface: "A confirmar",
    quickFacts: ["Corredor norte", "Ubicación estratégica", "Fácil acceso vial"],
    mapQuery: "-34.0897823,-59.0689081",
  },
  {
    id: "macrolotes",
    name: "Macrolotes",
    location: "Corredor norte y otros puntos del país",
    status: "Consultar disponibilidad",
    shortDescription: "Grandes superficies de tierra para proyectos de escala mayor.",
    description: "Grupo MEC comercializa macrolotes en distintos puntos del país, pensados para desarrolladores e inversores que buscan proyectos de mayor escala. (Descripción breve a completar con más detalle.)",
    image: "images/desarrollos/macrolotes-portada.jpg",
    images: ["images/desarrollos/macrolotes-portada.jpg", "ph-3", "ph-4", "ph-2"],
    features: ["Grandes superficies", "Aptos para desarrollo", "Ubicaciones estratégicas"],
    services: ["Servicios a definir según proyecto"],
    price: "Consultar disponibilidad",
    lots: "Consultar disponibilidad",
    surface: "A confirmar",
    quickFacts: ["Todo el país", "Grandes superficies", "Aptos para desarrollo"],
    mapQuery: "Buenos Aires, Argentina",
  },
  {
    id: "inversiones-pool-de-rentas",
    name: "Inversiones - Pool de Rentas",
    location: "Cataratas del Iguazú y Valle de Uco, Mendoza",
    status: "Consultar disponibilidad",
    shortDescription: "Oportunidades de inversión en hotelería y rentas en dos de los destinos turísticos de mayor proyección del país.",
    description: "Grupo MEC ofrece oportunidades de inversión en pool de rentas, con habitaciones hoteleras operadas por cadenas internacionales, locales comerciales y oficinas en Cataratas del Iguazú y en el Valle de Uco, Mendoza. (Descripción breve a completar con más detalle.)",
    image: "images/desarrollos/inversiones-pool-de-rentas-portada.jpg",
    images: ["images/desarrollos/inversiones-pool-de-rentas-portada.jpg", "ph-1", "ph-3", "ph-5"],
    features: [
      "Habitaciones hoteleras operadas por Marriott",
      "Pool de rentas",
      "Locales comerciales y oficinas",
      "Cataratas del Iguazú y Valle de Uco, Mendoza"
    ],
    services: ["Servicios a definir según proyecto"],
    price: "Consultar disponibilidad",
    lots: "Consultar disponibilidad",
    surface: "A confirmar",
    quickFacts: ["Pool de rentas", "Hotelería internacional", "Cataratas del Iguazú"],
    mapQuery: "Puerto Iguazú, Misiones, Argentina",
  }
];

// Utilidad para obtener un emprendimiento por id
function getDevelopmentById(id){
  return DEVELOPMENTS.find(d => d.id === id);
}
